version: 2
builds:
  - main: .
    binary: terraform-provider-unifi
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: Shiro-2000
    name: terraform-provider-unifi-v2
  extra_files:
    - glob: "./dist/terraform-provider-unifi*"